kind: Deployment
apiVersion: apps/v1
metadata:
  name: sap-server
  namespace: erp
  labels:
    app: sap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sap-server
  template:
    metadata:
      labels:
        app: sap-server
    spec:
      containers:
        - name: baw-sap-server
          ports:
            - containerPort: 3000
              name: http
          image: 'quay.io/linxianer12/baw-sap-server:0.0.5'
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          
---
kind: Service
apiVersion: v1
metadata:
  name: sap-server
  namespace: erp
  labels:
    app: sap-server
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: sap-server
  type: ClusterIP
